### ISSUE TITLE
[BUG]  Installation Ubuntu 22.04.1 LTS

### ISSUE THREAD

**Issue by marouamehri** [mad-lab-fau/mad-gui#13]
**Describe the bug**
Installation Ubuntu 22.04.1 LTS

./mad_gui_ubuntu
/tmp/_MEIFbXxto/mad_gui/utils/helper.py:66: UserWarning: Found a _MEI folder in /tmp, which has bee created <1 minute ago. Therefore, I assume this is called from a standalone executable. For this reason, I'm changing the resource path, from mad_gui/qt_designer/*.ui to mad_gui/qt_designer/build/*.py
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so: undefined symbol: g_tls_channel_binding_error_quark
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
/tmp/_MEIFbXxto/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libproxy.so.1)
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so

(mad_gui_ubuntu:141388): GLib-GIO-ERROR **: 10:18:09.387: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
Trace/breakpoint trap (core dumped)

**Comment by MalteOlle** [comment]
It seems to be related to PyQt on wayland / x11 but not to mad-gui specifically. You can find more information here:

- https://stackoverflow.com/questions/69828508/warning-ignoring-xdg-session-type-wayland-on-gnome-use-qt-qpa-platform-wayland
- https://forum.qt.io/topic/126731/what-is-this-warning
