### ISSUE TITLE
[BUG] mad-gui would not start on Windows 11 / user without admin rights

### ISSUE THREAD

**Issue by guillaumecalmon** [mad-lab-fau/mad-gui#14]
**Describe the bug**

mad-gui would not start on Windows 11 / user without admin rights

**To Reproduce**
I installed mad-gui using Anaconda powershell, it installed like a charm with one warning:

  WARNING: The scripts pyside2-designer.exe, pyside2-lupdate.exe, pyside2-rcc.exe and pyside2-uic.exe are installed in 'C:\Users\guill\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script mad-gui.exe is installed in 'C:\Users\guill\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed PySide2-5.15.1 mad-gui-1.0.1 pyqtgraph-0.11.0 python-vlc-3.0.18121 shiboken2-5.15.1 sphinx-qt-documentation-0.3 typing-extensions-3.10.0.2

I had to change directory to the path to the script
cd C:\Users\guill\AppData\Roaming\Python\Python39\Scripts

then when I launch mad-gui I received the following error:

qt.qpa.plugin: Could not load the Qt platform plugin "windows" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: direct2d, minimal, offscreen, windows.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

Thank you for any advice on how to fix this.

**Comment by MalteOlle** [comment]
To me, it seems that it was not installed in a conda environment. If it would have been installed in a conda environment, I would expect "\envs\" (e.g. C:\Users\<username>\.conda\envs\" to be on the path which describes the location of your python installation. Please make sure to 1. create a fresh conda environment 2. do not have any other python.exe on your path than the one from the activated conda environment while installing mad-gui. 

Hint: you can find out which python executables are on you PATH with `where python`
