### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Aksei** [mad-lab-fau/mad-gui#20]
**Describe the bug**
Problem with pandas.append function. Not available for pandas 2.0.0, only for lower versions.

Append was deprecated and removed in 2.0.0. Now, pandas.concat() should be used.

**Comment by AKuederle** [comment]
Can you try again? I think I found all concat cases. If not, please post the full error message, so that we can find the files/lines

**Comment by Aksei** [comment]
Yes, we just tried it. It works now  :)
Thank you!
