### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Aksei** [mad-lab-fau/mad-gui#8]
**Describe the bug**
We had a bug on window in mad_gui/windows/main.py line 69:

`if platform.system() == "Windows" and int(platform.release()) >= 8:`

platform.release() returns a string, and int(str) throws and error. We solved it by:  int(float(platform.release())).

**Comment by MalteOlle** [comment]
Thanks @Aksei  for mentioning the issue! Somehow I can not reproduce this. On my windows 10 machine with python 3.7 `int(platform.release())` works just fine as well as `int("10")`. What was the error you received?

**Comment by Aksei** [comment]
https://stackoverflow.com/questions/13861594/valueerror-invalid-literal-for-int-with-base-10  
Similar to this error. Also it was windows 8... that might a difference .... 
I checked that it is running with python 3.7

**Comment by MalteOlle** [comment]
should be fixed with 5bf8e17765e2ed56ad4747dae40380ab73cdf366
